version: '3.3'
services:
    server:
        build: MC_SERVER/.
        ports: 
            - "25565:25565"
            - "9225:9225"
    prometheus:
        build: Prometheus/.
        ports: 
            - "9090:9090"
    grafana:
        build: Grafana/.
        ports:
            - "3123:3000"